blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/YOUR_USERNAME/ha-sofabaton-hub/discussions
    about: Ask questions or discuss ideas
  - name: Documentation
    url: https://github.com/YOUR_USERNAME/ha-sofabaton-hub/blob/main/README.md
    about: Read the documentation
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Get help from the Home Assistant community

